title: Prolor | Security Blog
logo: /assets/img/logo.png
description: A blog to talk about security.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme